spring.application.name=app

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hexagonalArchitecture
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true